# general
batch_size: 256
input_size: 112
embd_shape: 512
sub_name: 'arc_mbv2_ccrop'
backbone_type: 'MobileNetV2' # 'ResNet50', 'MobileNetV2'
head_type: ArcHead # 'ArcHead', 'NormHead'
is_ccrop: True # central-cropping or not

# train
train_dataset: '/content/ms1m_bin.tfrecord'
binary_img: True
num_classes: 85742
num_samples: 5822653
epochs: 15
base_lr: 0.001
w_decay: !!float 5e-4
save_steps: 1000

# test
test_dataset: '/home/tupm/SSD/datasets/face_data'
